Fix prop velocity reset on save
CFC-Servers/cfc_prop_restoration pull request #8
Opened 2021-01-06 03:50 UTC by wrefgtzweve

2021-01-06 04:05 UTC, wrefgtzweve commented
The !saveprops command at line 235 is for testing purposes and should be remove when merging. Also ignore jenkins, it's failing on code that was already in the main branch.

2021-01-10 00:55 UTC, brandonsturgeon requested changes
Could you edit the description to explain how you tested it and how you verified it works? Helps a lot as a reviewer to know which parts of the code we should scrutinize. (i.e. if I knew you confirmed that it worked for 100% of your spawned props, I wouldn't have to consider that when I get to that part)

Just a few style suggestions and one little restructure.

Thanks for tackling this one!

2021-01-10 00:55 UTC, brandonsturgeon commented on lua/cfc_prop_restoration/core/sv/sv_init.lua
> +    if props == nil then return end
```suggestion
    if not props then return end

```

2021-01-10 00:55 UTC, brandonsturgeon commented on lua/cfc_prop_restoration/core/sv/sv_init.lua
> +        local propPhys = prop:GetPhysicsObject()
```suggestion
        local propPhys = prop:GetPhysicsObject()

```

2021-01-10 00:55 UTC, brandonsturgeon commented on lua/cfc_prop_restoration/core/sv/sv_init.lua
> +    playerProps = {}
```suggestion
    playerProps = {}

```

2021-01-10 00:55 UTC, brandonsturgeon commented on lua/cfc_prop_restoration/core/sv/sv_init.lua
> +            local propOwner = prop:CPPIGetOwner()
```suggestion
            local propOwner = prop:CPPIGetOwner()

```

2021-01-10 00:55 UTC, brandonsturgeon commented on lua/cfc_prop_restoration/core/sv/sv_init.lua
> +                table.insert(playerProps[propOwner], prop)
```suggestion
                table.insert( playerProps[propOwner], prop )
```

2021-01-10 00:55 UTC, brandonsturgeon commented on lua/cfc_prop_restoration/core/sv/sv_init.lua
> +            restorePropVelocities( propVelocities )
I think `getAllPlayerProps` should return the table of player props, and then you pass a table of each player's props into `getPropVelocities`

Something like this:
```suggestion
        local playerProps = getAllPlayerProps()

        for _, ply in pairs( player.GetHumans() ) do

            local propVelocities = getPropVelocities( playerProps[ply] )

            local success, props = xpcall( ADInterface.copy, notifyOnError( ply ), ply )
            success = success and props

            if success and not table.IsEmpty( props ) and props ~= nil then
                propData[ply:SteamID()] = props
                addPropDataToQueue( ply, props )
            end

            restorePropVelocities( propVelocities )
```

2021-01-10 01:02 UTC, plally requested changes

2021-01-10 01:02 UTC, plally commented on lua/cfc_prop_restoration/core/sv/sv_init.lua
> +                table.insert(playerProps[propOwner], prop)
```suggestion
                table.insert( playerProps[propOwner], prop )
```

2021-01-10 01:02 UTC, plally commented on lua/cfc_prop_restoration/core/sv/sv_init.lua
> +    if table.IsEmpty( playerProps[ply] ) then return end
```suggestion
    if table.IsEmpty( props ) then return end
```

2021-01-10 01:02 UTC, plally commented on lua/cfc_prop_restoration/core/sv/sv_init.lua
> +    if table.IsEmpty( playerProps[ply] ) then return end
I think it would be better if this returned an empty table instead of nil

one extra benefit of doing that is that you probably wouldn't need the `table.IsEmpty` checks

2021-01-10 02:16 UTC, wrefgtzweve commented on lua/cfc_prop_restoration/core/sv/sv_init.lua
> +    if props == nil then return end
Added

2021-01-11 16:30 UTC, wrefgtzweve reviewed
yes

2021-01-16 22:29 UTC, plally commented on lua/cfc_prop_restoration/core/sv/sv_init.lua
> +--end
it says remove after testing.

2021-01-20 02:49 UTC, plally approved these changes

2021-01-20 02:50 UTC, merged